version: 0.2

phases:
  install: 
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
      - go get github.com/sirupsen/logrus
  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - echo Compiling the Go code...
      - mkdir /go/src/testproject
      - cp -R $CODEBUILD_SRC_DIR /go/src
      - ls /go/src/testproject
      - go test ./...
      - go build /go/src/testproject/main.go -o testproject.bin
  post_build:
    commands:
      - ls /go/src/testproject
      - ./testproject.bin
      - echo Build completed on `date`
artifacts:
  files:
    - hello
