version: 0.2

phases:
  install: 
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
      - go get github.com/sirupsen/logrus
  build:
    commands:
      - echo Compiling the Go code...
      - mkdir /go/src/testproject
      - cp -R $CODEBUILD_SRC_DIR /go/src
      - cd /go/src/testproject
      - dep ensure -update
      - ls /go/src/testproject
      - go test ./...
      - cd /go/src/testproject
      
      - go build -o ./outbin
  post_build:
    commands:
      - ls /go/src/testproject
      - ./outbin
      - echo Build completed on `date`
artifacts:
  files:
    - hello
